### PR TITLE
Added gclient_s struct for plugins

### PR DESCRIPTION
**Pull request by k4r3l01**

### CODE REVIEW

**Comment by D4edalus** [comment]
what's your reasons to do that? I'd rather use Plugin functions to expose functionality as that is easier to maintain. Using plain structs will break plugins once we change something.

**Comment by T-Maxxx** [comment]
For plugins it must be included from ./src directory. Only this way we can be sure plugins using latest version of structure. And I'm sure pinc.h already includes this structure because no gclient manipulations will be available without that.

**Comment by k4r3l01** [comment]
so pinc.h dont including this i maked this because without this you will not find client team or client state and Ninja say me to make this

**Comment by k4r3l01** [comment]
and check declarations.h there is many declarations about client like client_t gentity etc but no gclient_s

**Comment by T-Maxxx** [comment]
It must not be doubled in main code and in declarations for plugins.

**Comment by IceNinjaman** [comment]
Well I have indeed told him that to include it and create a pull request. Also structures are indeed doubled already. They are structures of the CoD4 core engine. They will never change in a large extent unless you come up with a copy of the full CoD4 sourcecode...
Making for everything setter and getter functions is too much effort. Plugins creators have to be aware their plugins can break something or will get broken.

**Pull request merged**
