### PR TITLE
Added plugin events for game restart

### PR DESCRIPTION
**Pull request by proxict**

### CODE REVIEW

**Comment by K-Faktor** [comment]
What are the advantages of this update?

**Comment by proxict** [comment]
@K-Faktor The terminology here might be confusing, but game restart, in most mods anyways, means new round. So ultimately, this allows you to execute a callback on every round (either before the round end or after a new round start).

**Comment by K-Faktor** [comment]
> @K-Faktor The terminology here might be confusing, but game restart, in most mods anyways, means new round. So ultimately, this allows you to execute a callback on every round (either before the round end or after a new round start).

Thanks

**Comment by K-Faktor** [comment]
This update fixed this bug 
https://github.com/callofduty4x/CoD4x_Server/issues/397

**Pull request merged**
