### PR TITLE
[Plugin Maintainence #205] Fixed compilation

### PR DESCRIPTION
**Pull request by Kingwolf123**
Changes : 

1. Added pchat windows compile script.
2. Added cpp sample plugin windows compile script
3. Added missing function in warn plugin and windows compile scripts.
4. Fixed webapibanlist dependencies (q_shared.h) and added linux compile script

### CODE REVIEW

**Comment by D4edalus** [comment]
if you would be so kind also rename the windows compile scripts for all plugins to the same name please. like makewin32dll.cmd or whatever. 

and if you can manage to do so run the compile scripts in with the CI service
https://github.com/callofduty4x/CoD4x_Server/blob/master/appveyor.yml#L41

for comparison the linux script: https://github.com/callofduty4x/CoD4x_Server/blob/master/.travis.yml#L29

**Comment by Kingwolf123** [comment]
@D4edalus Check Now.. Appveyor is stuck i dont know what happened.

**Comment by D4edalus** [comment]
thanks for you changes, but its not yet building
[ ] https://ci.appveyor.com/project/D4edalus/cod4x-server/build/1.0.456#L854
[ ] the CI system doesn't report the errors because they aren't returned from the compile scripts. on linux that happens here: https://github.com/callofduty4x/CoD4x_Server/blob/master/plugins/antispam/makedll.sh#L11 for windows something like that might work https://stackoverflow.com/a/14905970

**Comment by Kingwolf123** [comment]
1- Aware of the compile failure on sourcebans plugins, but i dont know why.
2- I dont know powershell/batch at all, So i dont know how to update the batch files.

help would be appreciated.

**Comment by D4edalus** [comment]
Ok no problem, it's a great start. I will have time end next week and finish it. I will just keep the PR open until then.

**Comment by D4edalus** [comment]
continuing here: https://github.com/callofduty4x/CoD4x_Server/pull/227

**Pull request closed without merging**
