### PR TITLE
Added Dockerfile for building a docker image

### PR DESCRIPTION
**Pull request by cyberplant**

### CODE REVIEW

**Comment by T-Maxxx** [comment]
Let's discuss?
As I see Docker is quite useful thing but in case of closed source code, for pure binaries. You can just automate process of cloning and compiling repository if you need a lot of binaries for different rigs.

**Comment by D4edalus** [comment]
I'm playing for a while with the thought to create a docker image for the cod4x server. 

I dont see what docker has to do with closed source binaries?

### What I'd use it for
I would use it to have equally setup servers without the need of copy pasting folders and repairing symlinks whenever a new cod4x server needs to be created. the docker api also gives a cleaner interface to automation compared to my current solution which works through tmux.

### How I believe it works
To my understanding that docker file would just be executed once ( via `docker build` ). Then all those shell commands in the dockerfile are executed. That could either build the server, or just download the latest version from our autoupdate server. The result is a docker image. Once I have that image I can create multiple containers from an image. Whereas each container would be a running cod4 server. 

Creating a new container would need some configuration like: Setting volumes for main/zone, referencing a config file, setting commandlineoptions like maxplayer and serverport.

**Comment by cyberplant** [comment]
Exactly what @D4edalus said. It will allow to run different servers at the same time with only some different files. Also it allows us to run different versions of cod4x in parallel in a very easy way (for testing new releases or new features, for example).

I can provide some examples later if you want.

**Comment by cyberplant** [comment]
Why was this PR closed?

**Comment by T-Maxxx** [comment]
Its 20 days and no one of devs did not merged it. So I assume we're not agreed to add this file here. My point you can read in first comment.
@callofduty4x/dev What do you think?

**Comment by cyberplant** [comment]
I was waiting for the build to be fixed to continue working on this.

I can create a new PR from master, but if you're not interested on this, I can work on my own fork.

**Comment by D4edalus** [comment]
havent had time and motivation yet to look further into it. 
i still think it would be valuable to add it.

@cyberplant whats your scope of application for this?

**Comment by D4edalus** [comment]
could certainly be put as well into a different repository

**Comment by D4edalus** [comment]
new repo for docker stuff https://github.com/callofduty4x/cod4x_docker
@cyberplant add your pull requests there if you have any, ive added your inital file to it for now.

**Comment by cyberplant** [comment]
Thanks @D4edalus for this. As soon as I have some time I'll continue my work there.

**Pull request closed without merging**
