### PR TITLE
Small Fix: clientArchive

### PR DESCRIPTION
**Pull request by volkv**

### CODE REVIEW

**Comment by volkv** [comment]
ok :(

**Comment by T-Maxxx** [comment]
I didn't reviewed this PR, please, provide a small description. Is this mistype or what?

**Comment by volkv** [comment]
@T-Maxxx yep, small miss causing compile error which has been already corrected bypassing my PR
btw Iam little confused about how its possible, cus as I can see last commit to **sv_main.c** was like 5 months ago
что происходит блеать

**Comment by T-Maxxx** [comment]
У меня нет ошибок при сборке текущей версии.

**Comment by volkv** [comment]
Потому что, как было сказано - has been already corrected

**Pull request closed without merging**
